INSERT INTO HIBERUS.DEPARTAMENT (DEPARTAMENT_ID, DEPARTAMENT_NAME, DEPARTAMENT_STATUS)
SELECT 1, 'Sistema', 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.DEPARTAMENT WHERE DEPARTAMENT_NAME = 'Sistema'
);

INSERT INTO HIBERUS.DEPARTAMENT (DEPARTAMENT_ID, DEPARTAMENT_NAME, DEPARTAMENT_STATUS)
SELECT 2, 'Contabilidad', 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.DEPARTAMENT WHERE DEPARTAMENT_NAME = 'Contabilidad'
);

INSERT INTO HIBERUS.DEPARTAMENT (DEPARTAMENT_ID, DEPARTAMENT_NAME, DEPARTAMENT_STATUS)
SELECT 3, 'RRHH', 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.DEPARTAMENT WHERE DEPARTAMENT_NAME = 'RRHH'
);

INSERT INTO HIBERUS.DEPARTAMENT (DEPARTAMENT_ID, DEPARTAMENT_NAME, DEPARTAMENT_STATUS)
SELECT 4, 'People', 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.DEPARTAMENT WHERE DEPARTAMENT_NAME = 'People'
);


INSERT INTO HIBERUS.EMPLOYEE (DEPARTAMENT_ID, EMPLOYEE_NOMBRE, EMPLOYEE_LAST_NAME, AGE, SALARY, ROL, INIT_DATE, END_DATE, EMPLOYEE_STATUS)
SELECT 1, 'Nataly', 'Morales', 20, 700.0, 3, TO_DATE('13/01/2025', 'DD/MM/RRRR'), TO_DATE('13/05/2025', 'DD/MM/RRRR'), 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.EMPLOYEE
    WHERE EMPLOYEE_NOMBRE = 'Nataly' AND EMPLOYEE_LAST_NAME = 'Morales' AND INIT_DATE = TO_DATE('13/01/2025', 'DD/MM/RRRR')
);

INSERT INTO HIBERUS.EMPLOYEE (DEPARTAMENT_ID, EMPLOYEE_NOMBRE, EMPLOYEE_LAST_NAME, AGE, SALARY, ROL, INIT_DATE, END_DATE, EMPLOYEE_STATUS)
SELECT 1, 'Juan', 'Gonzales', 30, 800.0, NULL, TO_DATE('14/02/2025', 'DD/MM/RRRR'), TO_DATE('31/05/2025', 'DD/MM/RRRR'), 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.EMPLOYEE
    WHERE EMPLOYEE_NOMBRE = 'Juan' AND EMPLOYEE_LAST_NAME = 'Gonzales' AND INIT_DATE = TO_DATE('14/02/2025', 'DD/MM/RRRR')
);

INSERT INTO HIBERUS.EMPLOYEE (DEPARTAMENT_ID, EMPLOYEE_NOMBRE, EMPLOYEE_LAST_NAME, AGE, SALARY, ROL, INIT_DATE, END_DATE, EMPLOYEE_STATUS)
SELECT 1, 'Camila', 'Haro', 35, 999.0, NULL, TO_DATE('15/03/2025', 'DD/MM/RRRR'), TO_DATE('30/05/2025', 'DD/MM/RRRR'), 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.EMPLOYEE
    WHERE EMPLOYEE_NOMBRE = 'Camila' AND EMPLOYEE_LAST_NAME = 'Haro' AND INIT_DATE = TO_DATE('15/03/2025', 'DD/MM/RRRR')
);

INSERT INTO HIBERUS.EMPLOYEE (DEPARTAMENT_ID, EMPLOYEE_NOMBRE, EMPLOYEE_LAST_NAME, AGE, SALARY, ROL, INIT_DATE, END_DATE, EMPLOYEE_STATUS)
SELECT 2, 'Carlos', 'Guerra', 27, 700.0, 3, TO_DATE('13/04/2024', 'DD/MM/RRRR'), TO_DATE('13/05/2025', 'DD/MM/RRRR'), 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.EMPLOYEE
    WHERE EMPLOYEE_NOMBRE = 'Carlos' AND EMPLOYEE_LAST_NAME = 'Guerra' AND INIT_DATE = TO_DATE('13/04/2024', 'DD/MM/RRRR')
);

INSERT INTO HIBERUS.EMPLOYEE (DEPARTAMENT_ID, EMPLOYEE_NOMBRE, EMPLOYEE_LAST_NAME, AGE, SALARY, ROL, INIT_DATE, END_DATE, EMPLOYEE_STATUS)
SELECT 3, 'Jaime', 'Fuertes', 40, 800.0, NULL, TO_DATE('14/11/2024', 'DD/MM/RRRR'), TO_DATE('31/05/2025', 'DD/MM/RRRR'), 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.EMPLOYEE
    WHERE EMPLOYEE_NOMBRE = 'Jaime' AND EMPLOYEE_LAST_NAME = 'Fuertes' AND INIT_DATE = TO_DATE('14/11/2024', 'DD/MM/RRRR')
);

INSERT INTO HIBERUS.EMPLOYEE (DEPARTAMENT_ID, EMPLOYEE_NOMBRE, EMPLOYEE_LAST_NAME, AGE, SALARY, ROL, INIT_DATE, END_DATE, EMPLOYEE_STATUS)
SELECT 3, 'José', 'Andrade', 19, 999.0, NULL, TO_DATE('15/12/2024', 'DD/MM/RRRR'), TO_DATE('30/05/2025', 'DD/MM/RRRR'), 'A' FROM DUAL
WHERE NOT EXISTS (
    SELECT 1 FROM HIBERUS.EMPLOYEE
    WHERE EMPLOYEE_NOMBRE = 'José' AND EMPLOYEE_LAST_NAME = 'Andrade' AND INIT_DATE = TO_DATE('15/12/2024', 'DD/MM/RRRR')
);